### ISSUE TITLE
Catalog.txt error

### ISSUE THREAD

**Issue by tpmccallum** [Bookworm-project/BookwormDB#78]
I have the following error
```
Query failed: 
LOAD DATA LOCAL INFILE 'files/metadata/catalog.txt'
                       INTO TABLE catalog FIELDS ESCAPED BY ''
                       (bookid,filename,searchstring,date_year)
Traceback (most recent call last):
  File "OneClick.py", line 211, in <module>
    getattr(program,method)()
  File "OneClick.py", line 88, in database_metadata
    Bookworm.load_book_list()
  File "/var/www/html/mccallum/bookworm/CreateDatabase.py", line 181, in load_book_list
    self.variableSet.loadMetadata()
  File "/var/www/html/mccallum/bookworm/variableSet.py", line 682, in loadMetadata
    db.query(loadcode)
  File "/var/www/html/mccallum/bookworm/CreateDatabase.py", line 87, in query

```

**Comment by bmschmidt** [comment]
Hmm, it's hard to see what's going wrong here. Do you have anything in `/var/log/mysql/error.log` that might hint at the problem? Or maybe you could just open up mysql from the appropriate directory and try pasting in the query that failed to see what the error message is?

**Comment by tpmccallum** [comment]
Turns out this was an issue to do with encoding which we addressed in Issue 
https://github.com/Bookworm-project/BookwormDB/issues/77
